#!/bin/bash

all=0
good=0

for vettedfile in *.vetted; do
	basefile=`basename "$vettedfile" .vetted`

	basefile=`echo "$basefile" | sed -e 's/\!/\//g'`

	all=$(($all+1))

	if diff -u "$vettedfile" "$basefile"; then
		good=$(($good+1))
	else
		if [ "$1" = "fix" ]; then
			mv "$basefile" "$vettedfile"
		fi
	fi
done

cat <<END
===============================
all tests : $all
successful: $good
END

if [ "$all" -ne "$good" ]; then
	exit 1
else
	exit 0
fi
